DROP TABLE bookstore CASCADE;
DROP TABLE address CASCADE;
DROP TABLE billing CASCADE;
DROP TABLE publisher CASCADE;
DROP TABLE user_account CASCADE;
DROP TABLE book CASCADE;
DROP TABLE cart CASCADE;
DROP TABLE order_info CASCADE;

DROP TABLE book_in_cart CASCADE;
DROP TABLE sells CASCADE;
DROP TABLE owns CASCADE;
DROP TABLE book_in_order CASCADE;
DROP TABLE registered_at CASCADE;
DROP TABLE ord_address CASCADE;
